fos_rest:
    serializer:
        serialize_null: false
    routing_loader: false
    body_listener: true
    param_fetcher_listener: true
    view:
        view_response_listener:  true
        formats:
            html: true
            json: true
            xml: false
        mime_types:
            json: 'application/vnd.api+json'
    format_listener:
        rules:
            - { path: ^/, prefer_extension: false, fallback_format: html, priorities: [html] }
