jms_serializer:
    property_naming:
        id: 'jms_serializer.identical_property_naming_strategy'
    visitors:
        xml_serialization:
            format_output: '%kernel.debug%'
#     metadata:
#         auto_detection: false
#         directories:
#             App:
#                 namespace_prefix: "App"
#                 path: "%kernel.project_dir%/config/serializer"

# when@dev:
#     jms_serializer:
#         visitors:
#             json_serialization:
#                 options:
#                     - JSON_PRETTY_PRINT
#                     - JSON_UNESCAPED_SLASHES
#                     - JSON_PRESERVE_ZERO_FRACTION

# when@prod:
#     jms_serializer:
#         visitors:
#             json_serialization:
#                 options:
#                     - JSON_UNESCAPED_SLASHES
#                     - JSON_PRESERVE_ZERO_FRACTION
